root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  exclude_dir = ["bin", "tmp"]
  include_dir = []
  include_ext = ["go", "yaml"]
  delay = 500
  kill_delay = 10

[misc]
  clean_on_exit = false
