apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanoproxy
  namespace: nanoproxy
spec:
  selector:
    matchLabels:
      app: nanoproxy
  template:
    metadata:
      labels:
        app: nanoproxy
    spec:
      serviceAccount: nanoproxy
      containers:
        - name: proxy
          image: ghcr.io/benc-uk/nanoproxy-proxy:dev
          imagePullPolicy: Always
          env:
            - name: CONF_FILE
              value: /conf/config.yaml
            - name: DEBUG
              value: "true" # Probably disable/remove outside of testing
          resources:
            limits:
              memory: "256M"
              cpu: "1"

          ports:
            - containerPort: 8080

          volumeMounts:
            - mountPath: /conf/
              name: conf-volume

        - name: controller
          image: ghcr.io/benc-uk/nanoproxy-controller:dev
          imagePullPolicy: Always
          env:
            - name: CONF_FILE
              value: /conf/config.yaml
          resources:
            limits:
              memory: "256M"
              cpu: "1"
          volumeMounts:
            - mountPath: /conf/
              name: conf-volume

      volumes:
        - name: conf-volume
          emptyDir:
            medium: Memory
