apiVersion: v1
kind: ServiceAccount
metadata:
  name: nanoproxy
  namespace: nanoproxy

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nanoproxy
subjects:
  - kind: ServiceAccount
    name: nanoproxy
    namespace: nanoproxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nanoproxy

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nanoproxy
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingressclasses"]
    verbs: ["get", "watch", "list"]
