# -- Replica count
replicaCount: 1

ingressClass:
  # -- Create an IngressClass resource
  create: true
  # -- Name of the IngressClass resource
  name: nanoproxy

# -- Turn on debug logging in the proxy
debug: ""

tls:
  # -- Enable TLS on the proxy
  enabled: false
  # -- TLS secret name, must be set if enabled is true
  secretName: ""

image:
  # -- Prefix for the image repository, '-proxy' and '-controller' will be appended
  prefix: ghcr.io/benc-uk/nanoproxy
  # -- Image pull policy
  pullPolicy: Always
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- Set the imagePullSecrets value to enable pulling images from private registry
imagePullSecrets: []

# -- Override the release name used when creating resources
nameOverride: ""

# -- Override the fullname used when creating resources
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  # This will also create ClusterRole and ClusterRoleBinding for the service account
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of service account to use.
  # If not set and create is true, name is generated
  name: ""

# -- Pod annotations
podAnnotations: {}

# -- Security context for the pods
podSecurityContext: {}
  # fsGroup: 2000

# -- Security context for the containers
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # -- Type of service to create
  type: LoadBalancer

  # -- Port to expose on the service, change to 443 if using TLS
  port: 80

  # -- Use an existing IP address for the service
  loadBalancerIP:

resources:
  limits:
    # -- CPU resource limits
    cpu: 200m
    # -- Memory resource limits
    memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Node selector for pod assignment
nodeSelector: {}

# -- Tolerations for pod assignment
tolerations: []

# -- Affinity for pod assignment
affinity: {}
