{{- if .Values.ingressClass.create -}}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ingressClass.name }}
spec:
  # This controller name is hardcoded and should not be changed
  controller: benc-uk/nanoproxy
{{- end -}}