name: CI Pipeline

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "deploy/**"
      - "samples/**"
      - ".vscode/**"
      - "**/*.md"
      - "makefile"
  pull_request:
    branches: ["main"]

permissions:
  packages: write

jobs:
  # Lint and test the code on every push and PR
  lint-test:
    name: Lint and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Install tools
        run: make install-tools

      - name: Run linting
        run: make lint

      - name: Run tests
        run: make test

      - name: Run test report
        if: always()
        uses: robherley/go-test-action@v0.5.0

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: output/coverage.html

      - name: Run build
        run: make build

  # CI image builds of the main branch, tagged as dev
  image-build:
    name: Build and push images
    if: github.ref == 'refs/heads/main'
    env:
      IMAGE_REG: ghcr.io
      IMAGE_NAME: benc-uk/nanoproxy
      IMAGE_TAG: dev
      VERSION: main-branch
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4

      - name: Build images
        run: make images

      - name: Push images
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
          make push
