name: Release Images

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "change-me"
        type: string

env:
  # Note the version and image tag are the same
  IMAGE_TAG: ${{ github.event.release.tag_name || github.event.inputs.version }}
  VERSION: ${{ github.event.release.tag_name || github.event.inputs.version }}
  IMAGE_REG: ghcr.io
  IMAGE_NAME: benc-uk/nanoproxy

permissions:
  packages: write

jobs:
  image-build:
    name: Build and push images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set BUILD_INFO with date
        run: |
          echo BUILD_INFO="Stable build $(date --rfc-3339=seconds)" >> ${GITHUB_ENV}

      - run: |
          echo ===== RELEASE ======
          echo VERSION: $VERSION
          echo IMAGE_TAG: $IMAGE_TAG
          echo BUILD_INFO: $BUILD_INFO

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin

      - name: Build & push images
        run: make images push

      # We make `latest` tag point to the same version
      - name: Build & push latest
        env:
          IMAGE_TAG: latest
        run: make images push
